// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twjafgwcxtjpmshacfrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3amFmZ3djeHRqcG1zaGFjZnJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NTk3OTMsImV4cCI6MjA3MDEzNTc5M30.m9LqQC-imiLaTgzCxJcoFfeGMfs4ZlL6olpKwrodGJU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});